export const ADD_SPAWN = 'ADD_SPAWN'
export const CHANGE_SCENE = 'CHANGE_SCENE'
export const UPDATE_SELECTED = 'UPDATE_SELECTED'
export const MOVE_OBJECT = 'MOVE_OBJECT'
export const MOVE_UNDO = 'MOVE_UNDO'
export const CHANGE_ZONE = 'CHANGE_ZONE'